### ISSUE TITLE
状态刷新失败

### ISSUE THREAD

**Issue by smilingpoplar** [ARC-MX/sgcc_electricity_new#16]
```
024-06-28 10:44:59  [INFO    ] ---- 程序开始，当前仓库版本为1.4.1，仓库地址为https://github.com/ARC-MX/sgcc_electricity_new.git
2024-06-28 10:44:59  [INFO    ] ---- chromium-driver version is 120

...

2024-06-28 10:46:53  [INFO    ] ---- 将获取2户数据，user_id: ['<user_id_1>', '<user_id_2>']
...
2024-06-28 10:48:08  [INFO    ] ---- Get month power charge for <user_id_1> successfully, 2024-03-01-2024-03-31 usage is 58 KWh, charge is 24.89 CNY.
2024-06-28 10:48:08  [INFO    ] ---- Get month power charge for <user_id_1> successfully, 2024-04-01-2024-04-30 usage is 55 KWh, charge is 23.77 CNY.
2024-06-28 10:48:08  [INFO    ] ---- Get month power charge for <user_id_1> successfully, 2024-05-01-2024-05-31 usage is 54 KWh, charge is 23.47 CNY.

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='pane-second']/div[1]/div/label[2]/span[1]"}
  (Session info: chrome=120.0.6099.224)
Stacktrace:
#0 0x55e55c864233 <unknown>
#1 0x55e55c52e0fe <unknown>
#2 0x55e55c577ba6 <unknown>
#3 0x55e55c577cc1 <unknown>
#4 0x55e55c5c5204 <unknown>
#5 0x55e55c5a544d <unknown>
#6 0x55e55c5c2680 <unknown>
#7 0x55e55c5a51a3 <unknown>
#8 0x55e55c56a13e <unknown>
#9 0x55e55c56b712 <unknown>
#10 0x55e55c839534 <unknown>
#11 0x55e55c83c759 <unknown>
#12 0x55e55c83c238 <unknown>
#13 0x55e55c83cc05 <unknown>
#14 0x55e55c82babf <unknown>
#15 0x55e55c83cf8e <unknown>
#16 0x55e55c815c86 <unknown>
#17 0x55e55c8553e5 <unknown>
#18 0x55e55c8555cb <unknown>
#19 0x55e55c8637bf <unknown>
#20 0x7f212ddccea7 start_thread


#3 0x55e55c577cc1 <unknown>
#4 0x55e55c5c5204 <unknown>
#5 0x55e55c5a544d <unknown>
#6 0x55e55c5c2680 <unknown>
#7 0x55e55c5a51a3 <unknown>
#8 0x55e55c56a13e <unknown>
#9 0x55e55c56b712 <unknown>
#10 0x55e55c839534 <unknown>
#11 0x55e55c83c759 <unknown>
#12 0x55e55c83c238 <unknown>
#13 0x55e55c83cc05 <unknown>
#14 0x55e55c82babf <unknown>
#15 0x55e55c83cf8e <unknown>
#16 0x55e55c815c86 <unknown>
#17 0x55e55c8553e5 <unknown>
#18 0x55e55c8555cb <unknown>
#19 0x55e55c8637bf <unknown>
#20 0x7f212ddccea7 start_thread
. 5 retry times left.
2024-06-28 10:49:18  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/app/main.py", line 57, in run_task
    user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
TypeError: cannot unpack non-iterable NoneType object
^CTraceback (most recent call last):
  File "/app/main.py", line 90, in <module>
    main()
  File "/app/main.py", line 52, in main
    time.sleep(1)
```

**Comment by ARC-MX** [comment]
多用户吗？我这没有多用户的环境，没法调试多用户是否有bug。要不你先删掉一个用户试试

**Comment by smilingpoplar** [comment]
> 多用户吗？我这没有多用户的环境，没法调试多用户的情况。从代码看多用户显然是有Bug的，这是老仓库遗留下来的问题。要不你先删掉一个用户试试，等我闲了我再更新吧，最近比较忙。

我看了下国网页面，跟多用户无关。页面没有“近30天”的选项，
<img width="935" alt="截屏2024-06-28 17 39 04" src="https://github.com/ARC-MX/sgcc_electricity_new/assets/219728/a1336a63-9ac9-4600-9826-7aa019fff01f">
所以报错`Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='pane-second']/div[1]/div/label[2]/span[1]"}`

跟 issue #11  是一个问题

**Comment by ARC-MX** [comment]
这不是提示，请前往国网APP开通智能交费签约即可查看近30天日电量

**Comment by smilingpoplar** [comment]
本来想用try...except把下句包住试试，
```
# 30天用电量的数据
days_element = driver.find_elements(By.XPATH,
    "//*[@id='pane-second']/div[2]/div[2]/div[1]/div[3]/table/tbody/tr")  # 30天的值 列表 2023-05-0511.98

```
可遇到另一个经常遇到的问题，一直登录失败：
```
2024-06-28 18:08:52  [INFO    ] ---- Click the Agree option.
2024-06-28 18:09:23  [INFO    ] ---- Click login button.
2024-06-28 18:09:23  [INFO    ] ---- Get electricity canvas image successfully.
2024-06-28 18:09:24  [INFO    ] ---- Image CaptCHA distance is 101.
2024-06-28 18:09:55  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-06-28 18:09:55  [INFO    ] ---- Get electricity canvas image successfully.
2024-06-28 18:09:55  [INFO    ] ---- Image CaptCHA distance is 72.
2024-06-28 18:10:26  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-06-28 18:10:26  [INFO    ] ---- Get electricity canvas image successfully.
2024-06-28 18:10:27  [INFO    ] ---- Image CaptCHA distance is 231.
2024-06-28 18:10:58  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-06-28 18:10:58  [INFO    ] ---- Get electricity canvas image successfully.
2024-06-28 18:10:58  [INFO    ] ---- Image CaptCHA distance is 225.
2024-06-28 18:11:29  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-06-28 18:11:29  [INFO    ] ---- Get electricity canvas image successfully.
2024-06-28 18:11:29  [INFO    ] ---- Image CaptCHA distance is 236.
2024-06-28 18:12:00  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-06-28 18:12:00  [ERROR   ] ---- Login failed, maybe caused by Sliding CAPTCHA recognition failed
Traceback (most recent call last):
  File "/app/data_fetcher.py", line 244, in fetch
    return self._fetch()
            im_info = driver.execute_script(background_JS)
  File "/app/data_fetcher.py", line 267, in _fetch
    if self._login(driver):
  File "/app/data_fetcher.py", line 357, in _login
    raise Exception(
Exception: Login failed, maybe caused by 1.incorrect phone_number and password, please double check. or 2. network, please mnodify LOGIN_EXPECTED_TIME in .env and run docker compose up --build.
2024-06-28 18:12:01  [ERROR   ] ---- Webdriver quit abnormly, reason: Login failed, maybe caused by 1.incorrect phone_number and password, please double check. or 2. network, please mnodify LOGIN_EXPECTED_TIME in .env and run docker compose up --build.. 5 retry times left.
2024-06-28 18:12:01  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/app/main.py", line 57, in run_task
    user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
TypeError: cannot unpack non-iterable NoneType object
^CTraceback (most recent call last):
  File "/app/main.py", line 90, in <module>
    main()
  File "/app/main.py", line 52, in main
    time.sleep(1)
```

**Comment by smilingpoplar** [comment]
今天能登录了，测了下我两用户的账号能获取数据。提了个pull request #18 ，不支持30天用电量时，回退到7天。
