### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by liangfyx** [ARC-MX/sgcc_electricity_new#22]
运行环境：x86; Ikuai OS; Docker version 18.09.9
创建代码:
docker run -d \
  --env-file /etc/disk/1544065b-4f97-4283-809d-e7f29a0aeedd/Config/Docker/sgcc_electricity/config.env \
  --name sgcc_electricity \
  --network doc_docker_lan \
  -v /etc/disk/1544065b-4f97-4283-809d-e7f29a0aeedd/Config/Docker/sgcc_electricity/scripts:/app \
  -e SET_CONTAINER_TIMEZONE=true \
  -e CONTAINER_TIMEZONE=Asia/Shanghai \
  --restart unless-stopped \
  registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity:latest \
  python3 main.py
报错代码：If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
Traceback (most recent call last):  File "/app/main.py", line 13, in <module>
    from data_fetcher import DataFetcher
  File "/app/data_fetcher.py", line 29, in <module>
    from onnx import ONNX
  File "/app/onnx.py", line 4, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    from data_fetcher import DataFetcher
  File "/app/data_fetcher.py", line 29, in <module>
    from onnx import ONNX
  File "/app/onnx.py", line 4, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 57, in <module>
    raise import_capi_exception
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
Traceback (most recent call last):  File "/app/main.py", line 13, in <module>
    from data_fetcher import DataFetcher
  File "/app/data_fetcher.py", line 29, in <module>
    from onnx import ONNX
  File "/app/onnx.py", line 4, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    from data_fetcher import DataFetcher
  File "/app/data_fetcher.py", line 29, in <module>
    from onnx import ONNX
  File "/app/onnx.py", line 4, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 57, in <module>
    raise import_capi_exception
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
Traceback (most recent call last):  File "/app/main.py", line 13, in <module>
    from data_fetcher import DataFetcher
  File "/app/data_fetcher.py", line 29, in <module>
    from onnx import ONNX
  File "/app/onnx.py", line 4, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
AttributeError: _ARRAY_API not found
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    from data_fetcher import DataFetcher
  File "/app/data_fetcher.py", line 29, in <module>
    from onnx import ONNX
  File "/app/onnx.py", line 4, in <module>
    import onnxruntime
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 57, in <module>
    raise import_capi_exception
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError

**Comment by ARC-MX** [comment]
更新一下镜像再试一下
