### ISSUE TITLE
大佬 看看这是什么情况

### ISSUE THREAD

**Issue by cnmeeia** [ARC-MX/sgcc_electricity_new#39]
4-08-08 15:15:52  [ERROR   ] ---- Login failed, maybe caused by Sliding CAPTCHA recognition failed
Traceback (most recent call last):
  File "/app/data_fetcher.py", line 244, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 267, in _fetch
    if self._login(driver):
  File "/app/data_fetcher.py", line 358, in _login
    raise Exception(
Exception: Login failed, maybe caused by 1.incorrect phone_number and password, please double check. or 2. network, please mnodify LOGIN_EXPECTED_TIME in .env and run docker compose up --build.
2024-08-08 15:15:52  [ERROR   ] ---- Webdriver quit abnormly, reason: Login failed, maybe caused by 1.incorrect phone_number and password, please double check. or 2. network, please mnodify LOGIN_EXPECTED_TIME in .env and run docker compose up --build.. 5 retry times left.
2024-08-08 15:15:52  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/app/main.py", line 61, in run_task
    user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
TypeError: cannot unpack non-iterable NoneType object

**Comment by zjn9011** [comment]
遇到了类似问题，#47

**Comment by SummrWhit** [comment]
看了下，大概率是国网API接口的问题，这个不稳定，出现了，只能重启docker了
