### ISSUE TITLE
有充电桩账号时无法完整获取数据

### ISSUE THREAD

**Issue by mcok** [ARC-MX/sgcc_electricity_new#41]
Traceback (most recent call last):
  File "/app/data_fetcher.py", line 244, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 277, in _fetch
    last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list  = self._get_other_data(driver, user_id_list)
  File "/app/data_fetcher.py", line 438, in _get_other_data
    month_list.append(month[-1])
2024-08-21 10:12:40  [ERROR   ] ---- Webdriver quit abnormly, reason: 'NoneType' object is not subscriptable. 5 retry times left.
TypeError: 'NoneType' object is not subscriptable
2024-08-21 10:12:40  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/app/main.py", line 57, in run_task
    user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
TypeError: cannot unpack non-iterable NoneType object

账户里因为多了一个充电桩的号，导致不能完整获取数据。正好是开户后出错的

**Comment by ARC-MX** [comment]
我这也没有这种帐号，你说这问题我估计无法调试，可能需要你自己搞一下

**Comment by Ungs22** [comment]
> 我这也没有这种帐号，你说这个问题我估计无法调试，可能需要你自己搞一下

那请问下大佬能否修改下失败后的逻辑，遇到获取失败的户号后，就跳过该户号，执行后面的户号操作，不然一个户号失败以后所有获取成功的数据都提交不了给ha

**Comment by ARC-MX** [comment]
修复了一下，可以添加到环境变量中可忽略的ID中即可
