### ISSUE TITLE
运行报错Webdriver

### ISSUE THREAD

**Issue by Jacky910329** [ARC-MX/sgcc_electricity_new#51]
日志如图，翻了issues关了梯子还是这样，有大佬遇到同样问题不
2024-10-26 22:14:05  [INFO    ] ---- The current repository version is v1.5.0, and the repository address is https://github.com/ARC-MX/sgcc_electricity_new.git
2024-10-26 22:14:06  [INFO    ] ---- chromium-driver version is 120
2024-10-26 22:14:06  [INFO    ] ---- enable_database_storage is true, we will store the data to the database.
2024-10-26 22:14:06  [INFO    ] ---- The current logged-in user name isxxxx , the homeassistant address is http://xxxx:8123/, and the program will be executed every day at 07:00.
2024-10-26 22:14:06  [INFO    ] ---- Run job now! The next run will be at 07:00 and 19:00 every day
2024-10-26 22:14:06  [INFO    ] ---- patching driver executable /usr/bin/chromedriver
2024-10-26 22:14:18  [INFO    ] ---- Webdriver initialized.
Traceback (most recent call last):
  File "/app/data_fetcher.py", line 244, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 267, in _fetch
    if self._login(driver):
  File "/app/data_fetcher.py", line 303, in _login
    driver.get(LOGIN_URL)
  File "/usr/local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 621, in get_wrapped
    return orig_get(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 657, in get
    return super().get(url)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 441, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=120.0.6099.224)
Stacktrace:
#0 0x55987b3f4233 <unknown>
#1 0x55987b0be0fe <unknown>
#2 0x55987b0b6c66 <unknown>
#3 0x55987b0a8c05 <unknown>
#4 0x55987b0aa660 <unknown>
#5 0x55987b0a912e <unknown>
#6 0x55987b0a7fd7 <unknown>
#7 0x55987b0a7e6c <unknown>
#8 0x55987b0a6943 <unknown>
#9 0x55987b0a6d94 <unknown>
#10 0x55987b0c1662 <unknown>
#11 0x55987b152c56 <unknown>
#12 0x55987b135422 <unknown>
#13 0x55987b152680 <unknown>
#14 0x55987b1351a3 <unknown>
#15 0x55987b0fa13e <unknown>
#16 0x55987b0fb712 <unknown>
#17 0x55987b3c9534 <unknown>
#18 0x55987b3cc759 <unknown>
#19 0x55987b3cc238 <unknown>
#20 0x55987b3ccc05 <unknown>
#21 0x55987b3bbabf <unknown>
#22 0x55987b3ccf8e <unknown>
#23 0x55987b3a5c86 <unknown>
#24 0x55987b3e53e5 <unknown>
#25 0x55987b3e55cb <unknown>
#26 0x55987b3f37bf <unknown>
#27 0x7fd9d8185ea7 start_thread
2024-10-26 22:14:19  [ERROR   ] ---- Webdriver quit abnormly, reason: Message: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=120.0.6099.224)
Stacktrace:
#0 0x55987b3f4233 <unknown>
#1 0x55987b0be0fe <unknown>
#2 0x55987b0b6c66 <unknown>
#3 0x55987b0a8c05 <unknown>
#4 0x55987b0aa660 <unknown>
#5 0x55987b0a912e <unknown>
#6 0x55987b0a7fd7 <unknown>
#7 0x55987b0a7e6c <unknown>
#8 0x55987b0a6943 <unknown>
#9 0x55987b0a6d94 <unknown>
#10 0x55987b0c1662 <unknown>
#11 0x55987b152c56 <unknown>
#12 0x55987b135422 <unknown>
#13 0x55987b152680 <unknown>
#14 0x55987b1351a3 <unknown>
#15 0x55987b0fa13e <unknown>
#16 0x55987b0fb712 <unknown>
#17 0x55987b3c9534 <unknown>
#18 0x55987b3cc759 <unknown>
#19 0x55987b3cc238 <unknown>
#20 0x55987b3ccc05 <unknown>
#21 0x55987b3bbabf <unknown>
#22 0x55987b3ccf8e <unknown>
#23 0x55987b3a5c86 <unknown>
#24 0x55987b3e53e5 <unknown>
#25 0x55987b3e55cb <unknown>
#26 0x55987b3f37bf <unknown>
#27 0x7fd9d8185ea7 start_thread
. 5 retry times left.
Traceback (most recent call last):
  File "/app/main.py", line 61, in run_task
    user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
TypeError: cannot unpack non-iterable NoneType object
2024-10-26 22:14:19  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object

**Comment by even004** [comment]
前段时间折腾openwrt遇到你这情况了，是docker容器无法访问外网造成的。

**Comment by Jacky910329** [comment]
> 前段时间折腾openwrt遇到你这情况了，是docker容器无法访问外网造成的。

这个外网指的是墙呢还是说网络呢

**Comment by even004** [comment]
> > 前段时间折腾openwrt遇到你这情况了，是docker容器无法访问外网造成的。
> 
> 这个外网指的是墙呢还是说网络呢

不知道您是什么系统。我那时候用的是openwrt需要到防火墙把入站数据还有端口转发打开就可以了，原因就是容器没权限连接网络，建议你部署个其他需要连接网络运行的程序试下，我的是全部报错才这么解决的！他这个程序已经很牛批了！我现在armbian也在正常跑！

**Comment by Jacky910329** [comment]
> > > 前段时间折腾openwrt遇到你这情况了，是docker容器无法访问外网造成的。
> > 
> > 
> > 这个外网指的是墙呢还是说网络呢
> 
> 不知道您是什么系统。我那时候用的是openwrt需要到防火墙把入站数据还有端口转发打开就可以了，原因就是容器没权限连接网络，建议你部署个其他需要连接网络运行的程序试下，我的是全部报错才这么解决的！他这个程序已经很牛批了！我现在armbian也在正常跑！

感谢感谢，我是istoreos把转发调到接受正常运行了
