### ISSUE TITLE
后台运行十几个小时后报错，获取不到信息

### ISSUE THREAD

**Issue by SummrWhit** [ARC-MX/sgcc_electricity_new#65]
2024-12-13 07:03:58  [ERROR   ] ---- Get year power usage for 3203085294537 failed, pass
2024-12-13 07:03:58  [ERROR   ] ---- Get year power charge for 3203085294537 failed, pass
2024-12-13 07:05:08  [ERROR   ] ---- Get month power usage for 3203085294537 failed, pass
Traceback (most recent call last):
  File "/app/data_fetcher.py", line 244, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 279, in _fetch
2024-12-13 07:06:19  [ERROR   ] ---- Webdriver quit abnormly, reason: cannot unpack non-iterable NoneType object. 3 retry times left.
2024-12-13 07:06:19  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object
    last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list  = self._get_other_data(driver, user_id_list)
  File "/app/data_fetcher.py", line 423, in _get_other_data
    last_daily_datetime, last_daily_usage = self._get_yesterday_usage(driver)
TypeError: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/app/main.py", line 61, in run_task
    user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
TypeError: cannot unpack non-iterable NoneType object

**Comment by ARC-MX** [comment]
这是定时运行的，错了等着下次运行更新就行，每天运行两次
