### ISSUE TITLE
群晖 container  启动报错

### ISSUE THREAD

**Issue by solekg** [ARC-MX/sgcc_electricity_new#66]
报错信息：ERROR:root:Failing to read the .env file, the program will exit with an error message: 'NoneType' object has no attribute 'split'.

我将.env   库的scripts文件夹 及 docker-compose 放在一个文件夹内，下载镜像都很正常，但是无法启动，报错。

.env 信息如下： 

\### 以下项都需要修改
\## 国网登录信息
\# 修改为自己的登录账号
PHONE_NUMBER="XXX" 
\# 修改为自己的登录密码
PASSWORD="XXX" 
\# 排除指定用户ID，如果出现一些不想检测的ID或者有些充电、发电帐号、可以使用这个环境变量，如果有多个就用","分隔，","之间不要有空格
\# IGNORE_USER_ID=xxxxxxx,xxxxxxx,xxxxxxx

\# SQLite 数据库配置
\# or False 不启用数据库储存每日用电量数据。
ENABLE_DATABASE_STORAGE=True
\# 数据库名，默认为homeassistant
DB_NAME="homeassistant.db"
\# COLLECTION_NAME默认为electricity_daily_usage_{国网用户id}，不支持修改。

\## homeassistant配置
\# 改为你的localhost为你的homeassistant地址
HASS_URL="http://192.168.50.110:8123/" 
\# homeassistant的长期令牌
HASS_TOKEN="xxx"

\## selenium运行参数
\# 任务开始时间，24小时制，例如"07:00”则为每天早上7点执行，第一次启动程序如果时间晚于早上7点则会立即执行一次，每隔12小时执行一次。
JOB_START_TIME="07:00"

\## 其他默认参数
\# 浏览器默认等待时间，秒。
DRIVER_IMPLICITY_WAIT_TIME=60
\# 登录重试次数
RETRY_TIMES_LIMIT=5
\# 登录超时时间，秒
LOGIN_EXPECTED_TIME=60
RETRY_WAIT_TIME_OFFSET_UNIT=10

\## 日志级别
\# 例如“DEBUG”可以查看出错情况
LOG_LEVEL="INFO"

\## 记录的天数, 仅支持填写 7 或 30
\# 国网原本可以记录 30 天,现在不开通智能缴费只能查询 7 天造成错误
DATA_RETENTION_DAYS=7

\## 余额提醒
\# 是否缴费提醒
RECHARGE_NOTIFY=False
\# 余额
BALANCE=5.0
\# pushplus token 如果有多个就用","分隔，","之间不要有空格
\# PUSHPLUS_TOKEN=xxxxxxx,xxxxxxx,xxxxxxx

**Comment by hlhk2017** [comment]
同样出现这个问题
日志如下
`[+] Running 1/2
 ✔ Network sgcc_electricity_new_sgcc_network  Created                                                                                                                                                                                                                                                                                                0.4s 
 ⠴ Container sgcc_electricity                 Created                                                                                                                                                                                                                                                                                                0.5s 
Attaching to sgcc_electricity
sgcc_electricity  | docker-default
sgcc_electricity  | 2024-12-14 20:47:10  [INFO    ] ---- The current repository version is v1.5.3, and the repository address is https://github.com/ARC-MX/sgcc_electricity_new.git
sgcc_electricity  | 2024-12-14 20:47:12  [INFO    ] ---- chromium-driver version is 120
sgcc_electricity  | 2024-12-14 20:47:12  [INFO    ] ---- enable_database_storage is true, we will store the data to the database.
sgcc_electricity  | Traceback (most recent call last):
sgcc_electricity  |   File "/app/main.py", line 102, in <module>
sgcc_electricity  |     main()
sgcc_electricity  |   File "/app/main.py", line 44, in main
sgcc_electricity  |     fetcher = DataFetcher(PHONE_NUMBER, PASSWORD)
sgcc_electricity  |   File "/app/data_fetcher.py", line 157, in __init__
sgcc_electricity  |     self.IGNORE_USER_ID = os.getenv("IGNORE_USER_ID").split(",")
sgcc_electricity  | AttributeError: 'NoneType' object has no attribute 'split'`

也是内有属性split。
环境是HOAS 13.2.1
通过命令行直接安装

**Comment by ARC-MX** [comment]
> IGNORE_USER_ID

IGNORE_USER_ID这个属性需要参考example重新在.env中定义，自己添加一下吧

**Comment by ARC-MX** [comment]
> 账号密码都按实际的填，不晓得env这个文件里面到底哪里错了

你要么就把log日志传上来，要么就截图报错信息，我看这个啥也看不出来呀

**Comment by solekg** [comment]
> > IGNORE_USER_ID
> 
> 
> 
> IGNORE_USER_ID这个属性需要参考example重新在.env中定义，自己添加一下吧

我没有需要排除的id，所以直接#注释掉了，这个属性必须有吗？保留直接按默认的xxx吗？

**Comment by solekg** [comment]
> > 账号密码都按实际的填，不晓得env这个文件里面到底哪里错了
> 
> 
> 
> 你要么就把log日志传上来，要么就截图报错信息，我看这个啥也看不出来呀

报错信息只有这个“报错信息：ERROR:root:Failing to read the .env file, the program will exit with an error message: 'NoneType' object has no attribute 'split'.

”

**Comment by solekg** [comment]
> > 账号密码都按实际的填，不晓得env这个文件里面到底哪里错了
> 
> 
> 
> 你要么就把log日志传上来，要么就截图报错信息，我看这个啥也看不出来呀

log的日志报错信息只有这一条“报错信息：ERROR:root:Failing to read the .env file, the program will exit with an error message: 'NoneType' object has no attribute 'split'.

”

**Comment by ARC-MX** [comment]
> > > IGNORE_USER_ID
> > 
> > 
> > IGNORE_USER_ID这个属性需要参考example重新在.env中定义，自己添加一下吧
> 
> 我没有需要排除的id，所以直接#注释掉了，这个属性必须有吗？保留直接按默认的xxx吗？

必须要有，没有排除的你可以让后面是空或者xxxxx

**Comment by solekg** [comment]
> > > > IGNORE_USER_ID
> > > 
> > > 
> > > IGNORE_USER_ID这个属性需要参考example重新在.env中定义，自己添加一下吧
> > 
> > 
> > 我没有需要排除的id，所以直接#注释掉了，这个属性必须有吗？保留直接按默认的xxx吗？
> 
> 必须要有，没有排除的你可以让后面是空或者xxxxx

感谢大佬，搞定了

**Comment by youzi7** [comment]
请教个问题，直接在container里面找到了arcw_sgcc_electrictity镜像，启动后是不是只需要设置.env就可以了，这个.env文件应该放在哪个目录？谢谢

**Comment by solekg** [comment]
> 请教个问题，直接在container里面找到了arcw_sgcc_electrictity镜像，启动后是不是只需要设置.env就可以了，这个.env文件应该放在哪个目录？谢谢

.env、github的scripts文件夹、docker-compose 这三个放在一个文件夹内。用compose创建项目

**Comment by youzi7** [comment]
感谢回复，继续请教
![image](https://github.com/user-attachments/assets/62bf6a66-8902-4de8-b7a8-1f8a67954e45)
![image](https://github.com/user-attachments/assets/117c1ee0-89ea-40d4-b4c7-c4ee22d4e04c)
项目创建成功，也启动成功，但ha里面还是找不到相关实体（ha也是通过docker安装在群晖上）

**Comment by youzi7** [comment]
错误日志：
![image](https://github.com/user-attachments/assets/cf060956-7271-4b67-bbda-9de0aba5ffb5)

**Comment by ARC-MX** [comment]
> 错误日志： ![image](https://private-user-images.githubusercontent.com/12150367/397916489-cf060956-7271-4b67-bbda-9de0aba5ffb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3NzI0NDUsIm5iZiI6MTczNDc3MjE0NSwicGF0aCI6Ii8xMjE1MDM2Ny8zOTc5MTY0ODktY2YwNjA5NTYtNzI3MS00YjY3LWJiZGEtOWRlMGFiYTVmZmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDA5MDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNDBlNjllODFkZmNhMTUxNWM2NTQ1NzVkOTllNmZlYjQxZDg5YWFmN2FkYTZiNWI5NTRhYTVkZGNmNzFhYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uDMoTsGis4m4iwCw0filPU43HGh7MCA7Hp5dQmZ0MgQ)

.env里 都是些环境变量，你手动配置吧，这些问题都不是我这项目的问题，你要学习基础知识才能跑起来，docker-compose也可能翻译成docker命令的

**Comment by youzi7** [comment]
好的，非常感谢回复

**Comment by youzi7** [comment]
问题解决了，是最后那个pushtoken也必须要留，提醒下大家
另咨询下，好像没有读到峰谷，只有总数，上海电网的，一样吗？
<img width="760" alt="image" src="https://github.com/user-attachments/assets/e6cdf165-9cd1-4094-bc87-6b3c2a1b482e" />
