### ISSUE TITLE
docker报错 state-refresh task failed, reason is cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by Chinnshui93** [ARC-MX/sgcc_electricity_new#69]
报错log

：

Traceback (most recent call last):
  File "/app/data_fetcher.py", line 242, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 267, in _fetch
    if self._login(driver):
  File "/app/data_fetcher.py", line 350, in _login
    self._click_button(driver, By.XPATH, '//*[@id="login_box"]/div[1]/div[1]/div[2]/span')
  File "/app/data_fetcher.py", line 162, in _click_button
    click_element = driver.find_element(button_search_type, button_search_key)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="login_box"]/div[1]/div[1]/div[2]/span"}
  (Session info: chrome=120.0.6099.224)
Stacktrace:
#0 0x560f033d1233 <unknown>
#1 0x560f0309b0fe <unknown>
#2 0x560f030e4ba6 <unknown>
#3 0x560f030e4cc1 <unknown>
#4 0x560f03132204 <unknown>
#5 0x560f0311244d <unknown>
#6 0x560f0312f680 <unknown>
#7 0x560f031121a3 <unknown>
#8 0x560f030d713e <unknown>
#9 0x560f030d8712 <unknown>
#10 0x560f033a6534 <unknown>
#11 0x560f033a9759 <unknown>
#12 0x560f033a9238 <unknown>
#13 0x560f033a9c05 <unknown>
#14 0x560f03398abf <unknown>
#15 0x560f033a9f8e <unknown>
#16 0x560f03382c86 <unknown>
#17 0x560f033c23e5 <unknown>
#18 0x560f033c25cb <unknown>
#19 0x560f033d07bf <unknown>
#20 0x7f2128b1aea7 start_thread

Traceback (most recent call last):
  File "/app/main.py", line 61, in run_task
    user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
TypeError: cannot unpack non-iterable NoneType object
2024-12-15 19:18:36  [ERROR   ] ---- Webdriver quit abnormly, reason: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="login_box"]/div[1]/div[1]/div[2]/span"}
  (Session info: chrome=120.0.6099.224)
Stacktrace:
#0 0x560f033d1233 <unknown>
#1 0x560f0309b0fe <unknown>
#2 0x560f030e4ba6 <unknown>
#3 0x560f030e4cc1 <unknown>
#4 0x560f03132204 <unknown>
#5 0x560f0311244d <unknown>
#6 0x560f0312f680 <unknown>
#7 0x560f031121a3 <unknown>
#8 0x560f030d713e <unknown>
#9 0x560f030d8712 <unknown>
#10 0x560f033a6534 <unknown>
#11 0x560f033a9759 <unknown>
#12 0x560f033a9238 <unknown>
#13 0x560f033a9c05 <unknown>
#14 0x560f03398abf <unknown>
#15 0x560f033a9f8e <unknown>
#16 0x560f03382c86 <unknown>
#17 0x560f033c23e5 <unknown>
#18 0x560f033c25cb <unknown>
#19 0x560f033d07bf <unknown>
#20 0x7f2128b1aea7 start_thread
. 5 retry times left.
2024-12-15 19:18:36  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object

**Comment by ARC-MX** [comment]
你手动登录国网看看你又没有绑定电表吧

**Comment by Chinnshui93** [comment]
> 你手动登录国网看看你又没有绑定电表吧

有的，户号就一个，

今天更新后log

**Comment by ARC-MX** [comment]
更新就行
