### ISSUE TITLE
验证码无法验证问题

### ISSUE THREAD

**Issue by sulon007** [ARC-MX/sgcc_electricity_new#72]
昨天启动容器后的报错跟今天早上七点自动运行任务的报错是一样的，昨天在看到报错后，自己尝试用浏览器自己登录验证，可以正常登录。**今天在它尝试5次后，我再用浏览器也可以正常登录。**
不知道这个报错产生的具体原因是什么，对`.env`的配置也不能保证是否正确，还请有空了帮我分析一下
报错内容如下：
```shell
2024-12-19 07:00:14  [INFO    ] ---- Webdriver initialized.
2024-12-19 07:00:26  [INFO    ] ---- Open LOGIN_URL:https://www.95598.cn/osgweb/login.
2024-12-19 07:02:11  [INFO    ] ---- find_element 'user'.
2024-12-19 07:03:03  [INFO    ] ---- Click the Agree option.
2024-12-19 07:03:51  [INFO    ] ---- input_elements username : 186*******9.
2024-12-19 07:04:24  [INFO    ] ---- input_elements password : w**********M.
2024-12-19 07:05:07  [INFO    ] ---- Click login button.
2024-12-19 07:05:33  [INFO    ] ---- Get electricity canvas image successfully.
2024-12-19 07:05:34  [INFO    ] ---- Image CaptCHA distance is 293.
2024-12-19 07:06:12  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-12-19 07:07:22  [INFO    ] ---- Get electricity canvas image successfully.
2024-12-19 07:07:23  [INFO    ] ---- Image CaptCHA distance is 310.
2024-12-19 07:08:03  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-12-19 07:09:10  [INFO    ] ---- Get electricity canvas image successfully.
2024-12-19 07:09:11  [INFO    ] ---- Image CaptCHA distance is 93.
2024-12-19 07:09:47  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-12-19 07:10:56  [INFO    ] ---- Get electricity canvas image successfully.
2024-12-19 07:10:57  [INFO    ] ---- Image CaptCHA distance is 188.
2024-12-19 07:11:38  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-12-19 07:12:44  [INFO    ] ---- Get electricity canvas image successfully.
2024-12-19 07:12:45  [INFO    ] ---- Image CaptCHA distance is 111.
2024-12-19 07:13:23  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
2024-12-19 07:14:05  [ERROR   ] ---- Login failed, maybe caused by Sliding CAPTCHA recognition failed
2024-12-19 07:14:05  [INFO    ] ---- login unsuccessed !
2024-12-19 07:14:05  [INFO    ] ---- Login successfully on https://www.95598.cn/osgweb/login
Traceback (most recent call last):
  File "/app/data_fetcher.py", line 242, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 273, in _fetch
    user_id_list = self._get_user_ids(driver)
  File "/app/data_fetcher.py", line 488, in _get_user_ids
    self._click_button(driver, By.XPATH, "//div[@class='el-dropdown']/span")
  File "/app/data_fetcher.py", line 162, in _click_button
    click_element = driver.find_element(button_search_type, button_search_key)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 856, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='el-dropdown']/span"}
  (Session info: chrome=120.0.6099.224)
Stacktrace:
#0 0x00556afe4850 <unknown>
#1 0x00556aceb3e0 <unknown>
#2 0x00556ad2c42c <unknown>
#3 0x00556ad72400 <unknown>
#4 0x00556ad20904 <unknown>
#5 0x00556ad21d80 <unknown>
#6 0x00556afb9618 <unknown>
#7 0x00556afbc5f0 <unknown>
#8 0x00556afbc1d8 <unknown>
#9 0x00556afac304 <unknown>
#10 0x00556afbccb0 <unknown>
#11 0x00556af97858 <unknown>
#12 0x00556afd54c8 <unknown>
#13 0x00556afd56cc <unknown>
#14 0x00556afe3db4 <unknown>
#15 0x007f86c0a648 start_thread
#16 0x007f86445c9c <unknown>

Traceback (most recent call last):
  File "/app/main.py", line 61, in run_task
    user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
TypeError: cannot unpack non-iterable NoneType object
2024-12-19 07:15:28  [ERROR   ] ---- Webdriver quit abnormly, reason: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='el-dropdown']/span"}
  (Session info: chrome=120.0.6099.224)
Stacktrace:
#0 0x00556afe4850 <unknown>
#1 0x00556aceb3e0 <unknown>
#2 0x00556ad2c42c <unknown>
#3 0x00556ad72400 <unknown>
#4 0x00556ad20904 <unknown>
#5 0x00556ad21d80 <unknown>
#6 0x00556afb9618 <unknown>
#7 0x00556afbc5f0 <unknown>
#8 0x00556afbc1d8 <unknown>
#9 0x00556afac304 <unknown>
#10 0x00556afbccb0 <unknown>
#11 0x00556af97858 <unknown>
#12 0x00556afd54c8 <unknown>
#13 0x00556afd56cc <unknown>
#14 0x00556afe3db4 <unknown>
#15 0x007f86c0a648 start_thread
#16 0x007f86445c9c <unknown>
. 5 retry times left.
2024-12-19 07:15:28  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object
```

---
**更新一下：**
在编辑这个`issue`的时候发现我在`.env`中配置的密码不对，随即重新搞了一次，但报错内容完全一样。
有个疑问，为了验证密码错误会产生什么影响，特意用一个错误的账号和密码在浏览器登录，滑动验证码通过后，点登录，会提示`账号或密码错误，如连续输错5次，会被锁定20分钟`，但之前容器中尝试5次后，账号并没有被锁

更新到正确的密码后，报错如截图所示：
![image](https://github.com/user-attachments/assets/24282602-dee8-449b-ae88-ebcca25b0d52)

**下面是`.env`的内容：**
```shell
### 以下项都需要修改
## 国网登录信息
# 修改为自己的登录账号
PHONE_NUMBER="18********9"
# 修改为自己的登录密码
PASSWORD="w*********M."
IGNORE_USER_ID=33*******81

# SQLite 数据库配置
# or False 不启用数据库储存每日用电量数据。
ENABLE_DATABASE_STORAGE=True
# 数据库名，默认为homeassistant
DB_NAME="homeassistant.db"
# COLLECTION_NAME默认为electricity_daily_usage_{国网用户id}，不支持修改。

## homeassistant配置
# 改为你的localhost为你的homeassistant地址
HASS_URL="http://127.0.0.1:8123/"
# homeassistant的长期令牌
HASS_TOKEN="eyJhbGc**************************************************************************************************************************************************************************************ge2HvfUlirUU"

## selenium运行参数
# 任务开始时间，24小时制，例如"07:00”则为每天早上7点执行，第一次启动程序如果时间晚于早上7点则会立即执行一次，每隔12小时执行一次。
JOB_START_TIME="07:00"

## 其他默认参数
# 浏览器默认等待时间，秒。
DRIVER_IMPLICITY_WAIT_TIME=60
# 登录重试次数
RETRY_TIMES_LIMIT=5
# 登录超时时间，秒
LOGIN_EXPECTED_TIME=60
RETRY_WAIT_TIME_OFFSET_UNIT=10


## 日志级别
# 例如“DEBUG”可以查看出错情况
LOG_LEVEL="INFO"

## 记录的天数, 仅支持填写 7 或 30
# 国网原本可以记录 30 天,现在不开通智能缴费只能查询 7 天造成错误
DATA_RETENTION_DAYS=7

## 余额提醒
# 是否缴费提醒
RECHARGE_NOTIFY=Flase
# 余额
BALANCE=5.0
# pushplus token 如果有多个就用","分隔，","之间不要有空格
PUSHPLUS_TOKEN=32*******32,32************28
```

**Comment by ARC-MX** [comment]
硬件设备是什么，性能咋样，RETRY_WAIT_TIME_OFFSET_UNIT给大一点，给到15，这种一般都是登录成功了页面跳转太慢导致的，要么检查网络，要么增大等待时间

**Comment by sulon007** [comment]
> 硬件设备是什么，性能咋样，RETRY_WAIT_TIME_OFFSET_UNIT给大一点，给到15，这种一般都是登录成功了页面跳转太慢导致的，要么检查网络，要么增大等待时间

那我用电脑试试，昨天先是在电脑上弄的，报一样的错，但没发现密码配错了，电脑上的响应时间非常快，这个设备是家里的旁路有，上面跑的东西有点多
