### ISSUE TITLE
为什么在网页都能登陆 这上面一直登陆不上

### ISSUE THREAD

**Issue by dhf2587154870** [ARC-MX/sgcc_electricity_new#76]
sgcc_electricity  | 2024-12-19 16:36:41  [INFO    ] ---- input_elements username : 13xxxxxxxxxx.
sgcc_electricity  | 2024-12-19 16:37:14  [INFO    ] ---- input_elements password : cxxxxxx23.
sgcc_electricity  | 2024-12-19 16:37:55  [INFO    ] ---- Click login button.
sgcc_electricity  | 2024-12-19 16:38:20  [INFO    ] ---- Get electricity canvas image successfully.
sgcc_electricity  | 2024-12-19 16:38:21  [INFO    ] ---- Image CaptCHA distance is 213.
sgcc_electricity  | 2024-12-19 16:39:11  [INFO    ] ---- Sliding CAPTCHA recognition failed and reloaded.
sgcc_electricity  | Traceback (most recent call last):
sgcc_electricity  |   File "/app/data_fetcher.py", line 335, in fetch
sgcc_electricity  |     return self._fetch()
sgcc_electricity  |   File "/app/data_fetcher.py", line 371, in _fetch
sgcc_electricity  |     if self._login(driver):
sgcc_electricity  |   File "/app/data_fetcher.py", line 296, in _login
sgcc_electricity  |     self._click_button(driver, By.XPATH, '//*[@id="login_box"]/div[1]/div[1]/div[2]/span')
sgcc_electricity  |   File "/app/data_fetcher.py", line 162, in _click_button
sgcc_electricity  |     click_element = driver.find_element(button_search_type, button_search_key)
sgcc_electricity  |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 856, in find_element
sgcc_electricity  |     return self.execute(Command.FIND_ELEMENT, {
sgcc_electricity  |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
sgcc_electricity  |     self.error_handler.check_response(response)
sgcc_electricity  |   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
sgcc_electricity  |     raise exception_class(message, screen, stacktrace)
sgcc_electricity  | selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="login_box"]/div[1]/div[1]/div[2]/span"}
sgcc_electricity  |   (Session info: chrome=120.0.6099.224)
sgcc_electricity  | Stacktrace:
sgcc_electricity  | #0 0x0055873a4850 <unknown>
sgcc_electricity  | #1 0x0055870ab3e0 <unknown>
sgcc_electricity  | #2 0x0055870ec42c <unknown>
sgcc_electricity  | #3 0x005587132400 <unknown>
sgcc_electricity  | #4 0x0055870e0904 <unknown>
sgcc_electricity  | #5 0x0055870e1d80 <unknown>
sgcc_electricity  | #6 0x005587379618 <unknown>
sgcc_electricity  | #7 0x00558737c5f0 <unknown>
sgcc_electricity  | #8 0x00558737c1d8 <unknown>
sgcc_electricity  | #9 0x00558736c304 <unknown>
sgcc_electricity  | #10 0x00558737ccb0 <unknown>
sgcc_electricity  | #11 0x005587357858 <unknown>
sgcc_electricity  | #12 0x0055873954c8 <unknown>
sgcc_electricity  | #13 0x0055873956cc <unknown>
sgcc_electricity  | #14 0x0055873a3db4 <unknown>
sgcc_electricity  | #15 0x007fbe040648 start_thread
sgcc_electricity  | #16 0x007fbd87bc9c <unknown>
sgcc_electricity  | 
sgcc_electricity  | 2024-12-19 16:41:24  [ERROR   ] ---- Webdriver quit abnormly, reason: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="login_box"]/div[1]/div[1]/div[2]/span"}
sgcc_electricity  |   (Session info: chrome=120.0.6099.224)
sgcc_electricity  | Stacktrace:
sgcc_electricity  | #0 0x0055873a4850 <unknown>
sgcc_electricity  | #1 0x0055870ab3e0 <unknown>
sgcc_electricity  | #2 0x0055870ec42c <unknown>
sgcc_electricity  | #3 0x005587132400 <unknown>
sgcc_electricity  | #4 0x0055870e0904 <unknown>
sgcc_electricity  | #5 0x0055870e1d80 <unknown>
sgcc_electricity  | #6 0x005587379618 <unknown>
sgcc_electricity  | #7 0x00558737c5f0 <unknown>
sgcc_electricity  | #8 0x00558737c1d8 <unknown>
sgcc_electricity  | #9 0x00558736c304 <unknown>
sgcc_electricity  | #10 0x00558737ccb0 <unknown>
sgcc_electricity  | #11 0x005587357858 <unknown>
sgcc_electricity  | #12 0x0055873954c8 <unknown>
sgcc_electricity  | #13 0x0055873956cc <unknown>
sgcc_electricity  | #14 0x0055873a3db4 <unknown>
sgcc_electricity  | #15 0x007fbe040648 start_thread
sgcc_electricity  | #16 0x007fbd87bc9c <unknown>
sgcc_electricity  | . 5 retry times left.
sgcc_electricity  | 2024-12-19 16:41:24  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object
sgcc_electricity  | Traceback (most recent call last):
sgcc_electricity  |   File "/app/main.py", line 61, in run_task
sgcc_electricity  |     user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
sgcc_electricity  | TypeError: cannot unpack non-iterable NoneType object

w Enable Watch

**Comment by MemorXuxu** [comment]
被限制登录啦，隔一天再试吧

**Comment by dhf2587154870** [comment]
网页上都能登陆

MemorXuxu ***@***.***>于2024年12月19日 周四16:45写道：

**Comment by ARC-MX** [comment]
更新镜像吧
