### ISSUE TITLE
javascript error: Cannot read properties of null (reading 'childNodes')

### ISSUE THREAD

**Issue by w0330t** [ARC-MX/sgcc_electricity_new#81]
```
2024-12-20 10:31:37  [INFO    ] ---- The current repository version is v1.5.5, and the repository address is https://github.com/ARC-MX/sgcc_electricity_new.git
2024-12-20 10:31:37  [INFO    ] ---- chromium-driver version is 120
2024-12-20 10:31:37  [INFO    ] ---- enable_database_storage is true, we will store the data to the database.
2024-12-20 10:31:37  [INFO    ] ---- The current logged-in user name is "XXXXXX", the homeassistant address is "http://XXXXX:8123/" , and the program will be executed every day at 07:00.
2024-12-20 10:31:37  [INFO    ] ---- Run job now! The next run will be at 07:00 and 19:00 every day
2024-12-20 10:31:37  [INFO    ] ---- patching driver executable /usr/bin/chromedriver
2024-12-20 10:31:53  [INFO    ] ---- Webdriver initialized.
2024-12-20 10:31:55  [INFO    ] ---- Open LOGIN_URL:https://www.95598.cn/osgweb/login.
2024-12-20 10:32:10  [INFO    ] ---- find_element 'user'.
2024-12-20 10:32:26  [INFO    ] ---- Click the Agree option.
2024-12-20 10:32:41  [INFO    ] ---- input_elements username : "XXXXXX".
2024-12-20 10:32:41  [INFO    ] ---- input_elements password : "XXXXXX" .
2024-12-20 10:33:11  [INFO    ] ---- Click login button.
Traceback (most recent call last):
  File "/app/data_fetcher.py", line 335, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 371, in _fetch
    if self._login(driver):
  File "/app/data_fetcher.py", line 301, in _login
    im_info = driver.execute_script(background_JS)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 492, in execute_script
    return self.execute(command, {
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of null (reading 'childNodes')
  (Session info: chrome=120.0.6099.224)
Stacktrace:
#0 0x55776af9d233 <unknown>
#1 0x55776ac670fe <unknown>
#2 0x55776ac6d241 <unknown>
#3 0x55776ac6f28b <unknown>
#4 0x55776acfc495 <unknown>
#5 0x55776acde422 <unknown>
2024-12-20 10:33:11  [ERROR   ] ---- Webdriver quit abnormly, reason: Message: javascript error: Cannot read properties of null (reading 'childNodes')
  (Session info: chrome=120.0.6099.224)
Stacktrace:
#0 0x55776af9d233 <unknown>
#1 0x55776ac670fe <unknown>
#2 0x55776ac6d241 <unknown>
#3 0x55776ac6f28b <unknown>
#4 0x55776acfc495 <unknown>
#5 0x55776acde422 <unknown>
#6 0x55776acfb680 <unknown>
#7 0x55776acde1a3 <unknown>
#8 0x55776aca313e <unknown>
#6 0x55776acfb680 <unknown>
#9 0x55776aca4712 <unknown>
#7 0x55776acde1a3 <unknown>
#8 0x55776aca313e <unknown>
#9 0x55776aca4712 <unknown>
#10 0x55776af72534 <unknown>
#11 0x55776af75759 <unknown>
#12 0x55776af75238 <unknown>
#13 0x55776af75c05 <unknown>
#14 0x55776af64abf <unknown>
#15 0x55776af75f8e <unknown>
#16 0x55776af4ec86 <unknown>
#17 0x55776af8e3e5 <unknown>
#18 0x55776af8e5cb <unknown>
#19 0x55776af9c7bf <unknown>
#20 0x14e1e40eeea7 start_thread

#10 0x55776af72534 <unknown>
#11 0x55776af75759 <unknown>
#12 0x55776af75238 <unknown>
#13 0x55776af75c05 <unknown>
#14 0x55776af64abf <unknown>
#15 0x55776af75f8e <unknown>
#16 0x55776af4ec86 <unknown>
#17 0x55776af8e3e5 <unknown>
#18 0x55776af8e5cb <unknown>
#19 0x55776af9c7bf <unknown>
#20 0x14e1e40eeea7 start_thread
. 5 retry times left.
```

我大概看了一圈类似的issues，应该是没到验证码那一步，所以是网络问题吗？

**Comment by ARC-MX** [comment]
重启一下

**Comment by w0330t** [comment]
> 重启一下

重启什么？容器我重启了无数次了。需要把容器删掉重新构建吗？
